name: Publish to CapRover
on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test --if-present

      - name: Determine CapRover app and token based on tag
        id: app-info
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Version: $VERSION"
          if [[ "$GITHUB_REF" == refs/tags/* && "$VERSION" == *-* ]]; then
            echo "app=${{ secrets.MAIN_APP_NAME }}" >> $GITHUB_OUTPUT
            echo "token=${{ secrets.MAIN_APP_TOKEN }}" >> $GITHUB_OUTPUT
          else
            echo "app=${{ secrets.APP_NAME }}" >> $GITHUB_OUTPUT
            echo "token=${{ secrets.APP_TOKEN }}" >> $GITHUB_OUTPUT
          fi

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            captain-definition
            node_modules/
            package.json
            Dockerfile
            .silex.js
            client-config.js
            .nvmrc
            client-plugins
            server-plugins
            onboarding.json
          outPath: deploy.tar

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: ${{ steps.app-info.outputs.app }}
          token: ${{ steps.app-info.outputs.token }}
